version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "3360:3360"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - my_network
    environment:
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - my_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_volume:/var/www/html
    # ports:
    #   - "9000:9000"
    networks:
      - my_network
    environment:
      DB_NAME: ${MYSQL_DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_USER_PASSWORD}

networks:
  my_network:
    driver: bridge

volumes:
  wordpress_volume:
    driver_opts:
      type: volume
      o: bind
      device: /home/seokchoi/data/wordpress
  mariadb_volume:
    driver_opts:
    type: volume
    o: bind
    device: /home/seokchoi/data/mariadb
